app/kotti/docs/urls.py
from django.urls import path, include
from . import views


urlpatterns = [
    path('<page_name>/', views.page, name='page'),
    path('headers/<id>/delete/', views.header_delete, name='header_delete'),
    path('headers/<id>/', views.header_edit, name='header_edit'),
    path('headers/', views.header_new, name='header_new'),
    path('pages/<id>/delete/', views.page_delete, name='page_delete'),
    path('pages/<id>/', views.page_edit, name='page_edit'),
    path('pages/', views.page_new, name='page_new'),
    path('chapters/<id>/delete/', views.chapter_delete, name='chapter_delete'),
    path('chapters/<id>/', views.chapter_edit, name='chapter_edit'),
    path('chapters/', views.chapter_new, name='chapter_new'),
    path('sections/<id>/delete/', views.section_delete, name='section_delete'),
    path('sections/<id>/', views.section_edit, name='section_edit'),
    path('sections/', views.section_new, name='section_new'),
    path('', views.home, name='home'),
]

app/kotti/kotti/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework import routers
from main import api

router = routers.DefaultRouter()
router.register(r'room', api.RoomViewSet)
router.register(r'rooms', api.RoomList, basename='Room')
router.register(r'room_times', api.RoomTimeViewSet)
router.register(r'open_days', api.OpenDayViewSet)
router.register(r'open_times', api.OpenTimeViewSet)
router.register(r'booking', api.BookingViewSet)
router.register(r'users', api.KottiUserViewSet)


urlpatterns = [
    path('docs/', include('docs.urls')),
    path('api/', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

app/kotti/docs/models.py
from django.db import models


# Create your models here.
class DocsHeader(models.Model):
    title = models.CharField(max_length=100)
    order = models.IntegerField(default=0)

    class Meta:
        ordering = ['order']

    def __str__(self):
        return f'{self.title}'


class DocsPage(models.Model):
    header = models.ForeignKey(DocsHeader, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)

    class Meta:
        ordering = ['title']

    def __str__(self):
        return f'{self.title}'


class DocsChapter(models.Model):
    page = models.ForeignKey(DocsPage, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    order = models.IntegerField(default=0)

    class Meta:
        ordering = ['order']

    def __str__(self):
        return f'{self.title}'


class DocsSection(models.Model):
    chapter = models.ForeignKey(DocsChapter, on_delete=models.CASCADE)
    order = models.IntegerField(default=0)
    text = models.TextField(blank=True, default='')
    image = models.TextField(blank=True, default='')

    class Meta:
        ordering = ['order']

    def __str__(self):
        if len(self.text) > 100:
            text = self.text[:100] + '...'
        else:
            text = self.text
        return f'{text}'

app/kotti/docs/views.py
from django.shortcuts import render, redirect
from .models import *


# Create your views here.
def home(request):
    context = {
        'headers': DocsHeader.objects.all(),
        'pages': DocsPage.objects.all(),
        'chapters': DocsChapter.objects.all(),
        'page': None,
    }
    return render(request, 'docs/front.html', context)


def header_delete(request, id):
    header = DocsHeader.objects.get(id=id)
    header.delete()
    return redirect('/docs/')


def header_edit(request, id):
    header = DocsHeader.objects.get(id=id)

    if request.method == 'POST':
        header.title = request.POST['title'].lower()
        header.save()
        return redirect('/docs/')

    return redirect('/docs/')


def header_new(request):
    if request.method == 'POST':
        header = DocsHeader.objects.create(title=request.POST['title'].lower())
        header.save()
        return redirect('/docs/')


def page(request, page_name):
    page = DocsPage.objects.get(title=page_name)
    context = {
        'headers': DocsHeader.objects.all(),
        'pages': DocsPage.objects.all(),
        'chapters': DocsChapter.objects.all(),
        'page': page,
        'page_chapters': DocsChapter.objects.filter(page_id=page.id),
    }
    return render(request, 'docs/front.html', context)


def page_delete(request, id):
    page = DocsPage.objects.get(id=id)
    page.delete()
    return redirect('/docs/')


def page_edit(request, id):
    page = DocsPage.objects.get(id=id)

    if request.method == 'POST':
        page.title = request.POST['title'].lower()
        page.save()
        return redirect('/docs/' + page.title + '/')

    return redirect('/docs/' + page.title + '/')


def page_new(request):
    if request.method == 'POST':
        page = DocsPage.objects.create(title=request.POST['title'].lower(),
                                       header_id=request.POST['header_id'])
        page.save()
        return redirect('/docs/' + page.title + '/')


def chapter_delete(request, id):
    chapter = DocsChapter.objects.get(id=id)
    chapter.delete()
    return redirect('/docs/' + chapter.page.title + '/')


def chapter_edit(request, id):
    chapter = DocsChapter.objects.get(id=id)

    if request.method == 'POST':
        chapter.title = request.POST['title'].lower()
        chapter.save()
        return redirect('/docs/' + chapter.page.title + '/')

    return redirect('/docs/' + chapter.page.title + '/')


def chapter_new(request):
    if request.method == 'POST':
        chapter = DocsChapter.objects.create(title=request.POST['title'].lower(),
                                             page_id=request.POST['page_id'])
        chapter.save()
        chapter.page = DocsPage.objects.get(id=request.POST['page_id'])
        return redirect('/docs/' + chapter.page.title + '/')


def section_delete(request, id):
    section = DocsSection.objects.get(id=id)
    section.delete()
    return redirect('/docs/')


def section_edit(request, id):
    section = DocsSection.objects.get(id=id)

    if request.method == 'POST':

        if request.POST.get('text'):
            section.text = request.POST['text']
        if request.POST.get('image'):
            print(request.POST['image'])
        section.save()
        return redirect('/docs/')

    return redirect('/docs/')


def section_new(request):
    if request.method == 'POST':
        section = DocsSection.objects.create(text=request.POST['text'].lower(),
                                             order=request.POST['order'],
                                             chapter_id=request.POST['chapter_id'])
        section.save()
        return redirect('/docs/')

app/kotti/docs/templates/docs/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
    {% block title %}<title>Kotti User manual</title>{% endblock title %}
    <meta charset="UTF-8">
    {% load static %}

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css">
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css"
        integrity="sha512-xodZBNTC5n17Xt2atTPuE1HxjVMSvLVW9ocqUKLsCC5CXdbqCmblAshOMAS6/keqq/sMZMZ19scR4PsZChSR7A=="
        crossorigin=""/>
    <script src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js"
        integrity="sha512-XQoYMqMTK8LvdxXYG3nZ448hOEQiglfqkJs1NOQV44cWnUrBc8PkAOcXy20w0vlaXaVUearIOBhiXZ5V3ynxwA=="
        crossorigin=""></script>
    <script defer src="https://use.fontawesome.com/releases/v5.15.4/js/all.js"
        integrity="sha384-rOA1PnstxnOBLzCLMcre8ybwbTmemjzdNlILg8O7z1lUkLXozs4DHonlDtnE7fpc"
        crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"
        integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
        crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/ui/1.13.0/jquery-ui.min.js"
        integrity="sha256-hlKLmzaRlE8SCJC1Kw8zoUbU8BxA+8kR3gseuKfMjxA="
        crossorigin="anonymous"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body style="height: 100vh; overflow: none;">
<style>
#background {
    position: fixed;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    z-index: -1;
    background-color: #000;
    opacity: 0.5;
    background-image: url('{% static 'img/tausta.png' %}');
}
</style>
<div id="background"></div>
{% if user.is_authenticated %}
{% endif %}
{% block content %}{% endblock %}
{% if user.is_authenticated %}

{% else %}

{% endif %}
<div id="messages">{% include 'messages.html' %}</div>
<div style="position: fixed; right: 0.75rem; bottom: 0.75rem; font-size: 0.6rem; z-index: -1;">
    &copy;2022 Risto Lievonen, taustakuva Markus Kuoppala
</div>
</body>
</html>

app/kotti/docs/templates/docs/front.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<style>
ul ol {
    list-style: none;
}
</style>
<script>

</script>
<div class="columns" style="height: 100%; margin: 0px;">
    <div class="column p-2 is-1 has-text-centered">
        <div class="is-boxed">
            <img src="{% static 'img/logo.png' %}" style="max-width: 60px;">
        </div>
    </div>
    <div class="column is-quarter">
        <div class="box">
            <div class="block">
                <h4 class="title is-4" style="cursor: pointer;" onclick="location.href='/docs';">User manual</h4>
            </div>
            <div class="block">
                <aside class="menu">
                    {% for header in headers %}
                    <div class="m-2">
                        {% if page in header.docspage_set.all %}
                        <p class="menu-label" id="docs-label-{{ header.id }}" style="cursor: pointer;" onclick="docs_toggle_menu({{ header.id }})">
                            <span class="icon is-small"><i class="fas fa-angle-down"></i></span> {{ header.title }}
                        </p>
                        <ul class="menu-list" id="docs-menu-{{ header.id }}">
                        {% else %}
                        <p class="menu-label" id="docs-label-{{ header.id }}" style="cursor: pointer;" onclick="docs_toggle_menu({{ header.id }})">
                            <span class="icon is-small"><i class="fas fa-angle-right"></i></span> {{ header.title }}
                        </p>
                        <ul class="menu-list is-hidden" id="docs-menu-{{ header.id }}">
                        {% endif %}
                        {% for page in header.docspage_set.all %}
                            <li><a href="/docs/{{ page.title | lower | escape }}">{{ page.title | title }}</a></li>
                        {% endfor %}
                            <li class="docs-edit is-hidden">
                                <form method="post" action="/docs/new-page/">
                                    <input type="hidden" name="header_id" value="{{ header.id }}">
                                    {% csrf_token %}
                                    <div class="field has-addons">
                                        <div class="control is-expanded">
                                            <input class="input is-small" name="title" type="text" placeholder="New page..." autocomplete="no">
                                        </div>
                                        <div class="control">
                                            <button type="submit" class="button is-small is-success"><i class="fa fa-plus" title="Add..." onclick=""></i></button>
                                        </div>
                                    </div>
                                </form>
                            </li>
                        </ul>
                    </div>
                    {% endfor %}
                    <div class="docs-edit is-hidden">
                        <form method="post" action="/docs/new-header/">
                            {% csrf_token %}
                            <div class="field has-addons">
                                <div class="control is-expanded">
                                    <input class="input is-small" name="title" type="text" placeholder="New header..." autocomplete="no">
                                </div>
                                <div class="control">
                                    <button class="button is-small is-success"><i class="fa fa-plus" title="Add..." onclick=""></i></button>
                                </div>
                            </div>
                        </form>
                    </div>
                </aside>
            </div>
        </div>
    </div>
    <div class="column is-two-thirds">
        <div class="box" style="position: relative;">
            {% if user.is_superuser %}
            <button class="button is-primary is-small" style="position: absolute; top: 10px; right: 10px;" onclick="docs_toggle_edit();">Edit</button>
            {% endif %}
            {% if page %}
            <div class="block">
                <p><span class="icon is-small"><a href="/docs"><i class="fas fa-home"></i></a></span></p>
                <form method="post" action="/docs/pages/{{ page.id }}/delete/">
                    {% csrf_token %}
                    <button class="button is-small docs-edit is-hidden is-danger" style="position: absolute; top: 10px; right: 65px;" type="submit"><i class="fa fa-trash" title="Delete..."></i></button>
                </form>
                <button class="button is-success is-small docs-edit is-hidden" style="position: absolute; top: 10px; right: 110px;" title="Save" onclick="docs_save_page();"><i class="fas fa-save"></i></button>
            </div>
            <form id="docs-page-form" method="post" action="/docs/pages/{{ page.id }}/">
                {% csrf_token %}
                <div class="block">
                    <h2 class="title docs-view is-4">{{ page.title | title }}</h2>
                    <input class="input docs-edit is-hidden" name="title" type="text" value="{{ page.title }}">
                </div>
            </form>
            <hr>
            {% for chapter in page.docschapter_set.all %}
            <form method="post" action="/docs/chapters/{{ chapter.id }}/">
                {% csrf_token %}
                <div class="block" style="position: relative;">
                    <h3 class="title docs-view is-5">{{ chapter.title | title }}<a name="{{ chapter.title | lower }}">&nbsp;</a></h3>
                    <div class="field has-addons docs-edit is-hidden">
                        <div class="control is-expanded">
                            <input class="input" name="title" type="text" value="{{ chapter.title }}">
                        </div>
                        <div class="control">
                            <button class="button is-success" type="submit"><i class="fa fa-save" title="Save..."></i></button>
                            <button class="button is-danger" type="button" onclick="docs_delete_chapter({{ chapter.id }})"><i class="fa fa-trash" title="Delete..."></i></button>
                        </div>
                    </div>
                </div>
            </form>
            {% for section in chapter.docssection_set.all %}
            <form method="post" action="/docs/sections/{{ section.id }}/">
                {% csrf_token %}
                <div class="block mb-3" style="position: relative;">
                    <p class="docs-view">{{ section.text }}</p>
                    <textarea class="textarea docs-edit is-hidden" name="text">{{ section.text }}</textarea>
                    <button class="button is-success is-small docs-edit is-hidden" title="Save"><i class="fas fa-save"></i></button>
                </div>
            </form>
            {% endfor %}
            <hr>
            {% endfor %}
            {% else %}
            <div class="content">
                <h3 class="title">User manual</h3>
                <hr>
                <h5>Site map</h5>
                <ul>
                    {% for header in headers %}
                    <li>
                        {{ header.title | title }}
                        <ul>
                        {% for page in header.docspage_set.all %}
                            <li><a href="/docs/{{ page.title | lower | escape }}">{{ page.title | title }}</a></li>
                        {% endfor %}
                        </ul>
                    </li>
                    {% endfor %}
                </ul>
            </div>
            {% endif %}
            <div class="content">

            </div>
        </div>
    </div>
</div>
<script>

var edit_mode = false;
function docs_toggle_edit() {
    edit_mode = !edit_mode;
    if(edit_mode) {
        $(".docs-edit").removeClass("is-hidden");
        $(".docs-view").addClass("is-hidden");
    } else {
        $(".docs-edit").addClass("is-hidden");
        $(".docs-view").removeClass("is-hidden");
    }
}

function docs_toggle_menu(id) {
    $(".menu-list").addClass("is-hidden");
    $(".fa-angle-down").removeClass("fa-angle-down").addClass("fa-angle-right");
    $("#docs-label-" + id + " svg").removeClass("fa-angle-right").addClass("fa-angle-down");
    $("#docs-menu-" + id).removeClass("is-hidden");
}

function docs_save_page() {
    $("#docs-page-form").submit();
}

function docs_delete_chapter(id) {
    location.href = "/docs/chapters/" + id + "/delete/";
}

</script>
{% endblock %}